spring:
  application:
    name: jooq
  #flyway:
   # enabled: true
   # baseline-on-migrate: true
   # url: jdbc:mysql://localhost:3306/jooqtest?serverTimezone=UTC&characterEncoding=UTF-8
   # user: root
   # password: 1234
   # locations: resources/db/migration
   # baseline-version: 0
  datasource:
    # 1. DB 접속 주소 (jooqtest 스키마)
    url: jdbc:mysql://localhost:3306/jooqtest?serverTimezone=UTC&characterEncoding=UTF-8
    # 2. 아이디와 비밀번호
    username: root
    password: 1234
    # 3. 드라이버 클래스 이름 (생략해도 되지만 명시하는 게 좋다요)
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    stream:
      host: localhost
      port: 5552  # Stream 포트
      username: guest
      password: guest

logging:
  level:
    org.springframework.messaging.simp.config: DEBUG
    org.springframework.messaging.simp.broker: DEBUG